"""Export utilities for reports, experiment results, and ATT&CK Navigator layers."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from .config_loader import OUTPUT_DIR
from .mitre_mapper import build_navigator_technique_entries


def ensure_output_dirs() -> None:
    (OUTPUT_DIR / "figures").mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "reports").mkdir(parents=True, exist_ok=True)


def _write_json(path: Path, payload: dict[str, Any]) -> Path:
    ensure_output_dirs()
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path


def export_prediction_report_json(
    selected_profile: str,
    scenario_name: str,
    noise_rate: float,
    missing_rate: float,
    observed_alerts: list[str],
    predicted_path: list[str],
    current_state_distribution: dict[str, float],
    next_state_distribution: dict[str, float],
    mitre_techniques: list[dict[str, Any]],
    explanation: dict[str, Any],
    caveats: list[str] | None = None,
    path: Path | None = None,
) -> Path:
    payload = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "selected_profile": selected_profile,
        "scenario_name": scenario_name,
        "noise_rate": noise_rate,
        "missing_rate": missing_rate,
        "observed_alerts": observed_alerts,
        "predicted_path": predicted_path,
        "current_state_distribution": current_state_distribution,
        "next_state_distribution": next_state_distribution,
        "mitre_techniques": mitre_techniques,
        "explanation": explanation,
        "caveats": caveats or explanation.get("caveats", []),
    }
    return _write_json(path or OUTPUT_DIR / "prediction_report.json", payload)


def export_prediction_report_markdown(
    selected_profile: str,
    scenario_name: str,
    observed_alerts: list[str],
    predicted_path: list[str],
    explanation: dict[str, Any],
    mitre_techniques: list[dict[str, Any]],
    path: Path | None = None,
) -> Path:
    ensure_output_dirs()
    lines = [
        "# ATT&CK-HMM Prediction Report",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        f"Profile: {selected_profile}",
        f"Scenario: {scenario_name}",
        "",
        "## Executive Summary",
        explanation.get("executive_summary", ""),
        "",
        "## Analyst Explanation",
        explanation.get("analyst_explanation", ""),
        "",
        "## Observed Alerts",
        "\n".join(f"- {alert}" for alert in observed_alerts),
        "",
        "## Predicted Hidden Path",
        "\n".join(f"{i + 1}. {state}" for i, state in enumerate(predicted_path)),
        "",
        "## Top MITRE ATT&CK Techniques",
        "\n".join(
            f"- {item['technique_id']} {item['technique_name']} ({item['score']})"
            for item in mitre_techniques[:10]
        ),
        "",
        "## Caveats",
        "\n".join(f"- {item}" for item in explanation.get("caveats", [])) or "- None",
        "",
    ]
    out = path or OUTPUT_DIR / "prediction_report.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def export_experiment_results_csv(results: pd.DataFrame, path: Path | None = None) -> Path:
    ensure_output_dirs()
    out = path or OUTPUT_DIR / "experiment_results.csv"
    results.to_csv(out, index=False)
    return out


def export_attack_navigator_layer(technique_scores: list[dict[str, Any]], path: Path | None = None) -> Path:
    layer = {
        "name": "ATT&CK-HMM Prediction Layer",
        "versions": {"attack": "enterprise", "navigator": "4.5", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "Predicted MITRE ATT&CK techniques generated by ATT&CK-HMM.",
        "techniques": build_navigator_technique_entries(technique_scores),
    }
    return _write_json(path or OUTPUT_DIR / "attack_navigator_layer.json", layer)


def export_session_state_as_json(session_state: dict[str, Any], path: Path | None = None) -> Path:
    return _write_json(path or OUTPUT_DIR / "reports" / "session_state.json", session_state)

